

import 'package:fest_app/core/models/timeline_model.dart';

const List<FestEvent> patnaEvents = [
  FestEvent(
      date: "14th Feb",
      title: "Qua - Badminton (M & W)",
      time: "04:30pm to 8:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "15th Feb",
      title: "Qua - Badminton (M & W)",
      time: "10:30am to 2:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "15th Feb",
      title: "Chess (M & W)",
      time: "10:30am to 2:30pm",
      venue: "Boys Room",
      club: "Student Recreation Club"),
  FestEvent(
      date: "16th Feb",
      title: "Final - Badminton (M & W)",
      time: "10:30am to 2:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "16th Feb",
      title: "Chess (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Boys Room",
      club: "Student Recreation Club"),
  FestEvent(
      date: "17th Feb",
      title: "Chess (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Boys Room",
      club: "Student Recreation Club"),
  FestEvent(
      date: "9th March",
      title: "Fest Revealation Ceremony",
      time: "TBD",
      venue: "TBD",
      club: "All Clubs"),
  FestEvent(
      date: "16th March",
      title: "Qua - Volleyball (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "16th March",
      title: "Qua - Table tennis (M & W)",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "16th March",
      title: "Pre-Solo Singing",
      time: "5:30 to 8:30pm",
      venue: "TBD",
      club: "Not Specified"),
  FestEvent(
      date: "16th March",
      title: "Pre-Duet Singing & Instrumental",
      time: "5:30 to 8:30pm",
      venue: "CV Raman Hall",
      club: "Music Club"),
  FestEvent(
      date: "17th March",
      title: "Qua - Volleyball (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "17th March",
      title: "Qua - Table tennis (M & W)",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "17th March",
      title: "Pre-Solo Dance",
      time: "5:30 to 8:30pm",
      venue: "TBD",
      club: "Dance Club"),
  FestEvent(
      date: "17th March",
      title: "Pre-Duet/Group Dance",
      time: "5:30 to 8:30pm",
      venue: "CV Raman Hall",
      club: "Dance Club"),
  FestEvent(
      date: "18th March",
      title: "Final-Table tennis (M & W)",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "18th March",
      title: "Yogasana Competition (M)",
      time: "5:30 to 8:30pm",
      venue: "Boys Room",
      club: "Yoga & Meditation Club"),
  FestEvent(
      date: "19th March",
      title: "Pre-Mimicry/Standup",
      time: "5:30 to 8:30pm",
      venue: "CV Raman Hall",
      club: "Drama Club"),
  FestEvent(
      date: "19th March",
      title: "Final - Volleyball (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "20th March",
      title: "Qua-Mixed Cricket",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Outdoor Club & Student Recreation Club"),
  FestEvent(
      date: "20th March",
      title: "Power Sports (W)",
      time: "5:30 to 8:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "20th March",
      title: "Pre-MonoAct/Duo Act",
      time: "5:30 to 8:30pm",
      venue: "CV Raman Hall",
      club: "Drama Club"),
  FestEvent(
      date: "21th March",
      title: "Qua - Mixed Cricket",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Student Recreation Club"),
  FestEvent(
      date: "21th March",
      title: "Clay modelling & No brushes",
      time: "10:30am to 2:30pm",
      venue: "Infront of Ganga Hostel",
      club: "Literary & Art Club"),
  FestEvent(
      date: "21st March",
      title: "Photography Events",
      time: "10:30am to 2:30pm",
      venue: "Meghnath Saha hall",
      club: "Photography & Media"),
  FestEvent(
      date: "22st March",
      title: "Face painting & Tshirt painting",
      time: "10:30am to 2:30pm",
      venue: "Infront of Ganga Hostel",
      club: "Literary & Art Club"),
  FestEvent(
      date: "22st March",
      title: "Designing Events",
      time: "10:30am to 2:30pm",
      venue: "CV Raman Hall",
      club: "Photography & Media"),
  FestEvent(
      date: "22nd March",
      title: "Qua Football (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "23nd March",
      title: "Pre-Pratibimb",
      time: "5:30 to 8:30pm",
      venue: "CV Raman Hall",
      club: "All Clubs"),
  FestEvent(
      date: "23nd March",
      title: "Qua - Tug of War (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "23rd March",
      title: "Yogasana Competition (W)",
      time: "5:30 to 8:30pm",
      venue: "Boys Room",
      club: "Yoga & Meditation Club"),
  FestEvent(
      date: "24rd March",
      title: "Power Sports (W)",
      time: "5:30 to 8:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "24th March",
      title: "Debate (English)",
      time: "10:30am to 2:30pm",
      venue: "CWRS, 2nd Floor",
      club: "Literary & Art Club / Think India"),
  FestEvent(
      date: "25th March",
      title: "Qua Football (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "25th March",
      title: "Qua - TT Mixed Doubles",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "25th March",
      title: "Pre-Sher o Shayari & Poetry",
      time: "5:30 to 8:30pm",
      venue: "Meghnath Saha hall",
      club: "Literary & Art Club / Think India"),
  FestEvent(
      date: "26th March",
      title: "Final Football (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "26th March",
      title: "Final Sher o Shayari & Poetry",
      time: "5:30 to 8:30pm",
      venue: "Meghnath Saha hall",
      club: "Literary & Art Club / Think India"),
  FestEvent(
      date: "26th March",
      title: "Qua - Tug of War (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "27th March",
      title: "Pre - Pratibimb",
      time: "5:30 to 8:30pm",
      venue: "Boys Room",
      club: "All Clubs"),
  FestEvent(
      date: "27th March",
      title: "Final-TT Mixed Doubles",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "27th March",
      title: "Final Tug of War (M&W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "28th March",
      title: "Buffer Time",
      time: "10:30am to 2:30pm",
      venue: "TBD",
      club: "All Clubs"),
  FestEvent(
      date: "28th March",
      title: "Antakshari",
      time: "5:30 to 8:30pm",
      venue: "Meghnath Saha hall",
      club: "Music Club"),
  FestEvent(
      date: "28th March",
      title: "Power Sports (M)",
      time: "10:30am to 2:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "28th March",
      title: "Qua - Badminton Mixed Doubles",
      time: "5:30 to 8:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "28th March",
      title: "E-Sports",
      time: "TBD",
      venue: "TBD",
      club: "Outdoor Club"),
  FestEvent(
      date: "29th March",
      title: "Debate (Hindi)",
      time: "5:30 to 8:30pm",
      venue: "CWRS, 2nd Floor",
      club: "Literary & Art Club / Think India"),
  FestEvent(
      date: "29th March",
      title: "Power Sports (M)",
      time: "10:30am to 2:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "29th March",
      title: "Nukkad Natak & Flash Mob",
      time: "4:30 pm to 6:30 pm",
      venue: "Main Building",
      club: "Drama & Dance Club"),
  FestEvent(
      date: "30th March",
      title: "Final-Badminton Mixed Doubles",
      time: "5:30 to 8:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "30th March",
      title: "Qua - Kabaddi (M & W)",
      time: "5:30 to 8:30pm",
      venue: "OAT",
      club: "Student Recreation Club"),
  FestEvent(
      date: "30th March",
      title: "Twig n Twine",
      time: "5:30 to 8:30pm",
      venue: "SAC",
      club: "Literary & Art Club & Environment Club"),
  FestEvent(
      date: "30th March",
      title: "Film making & Drama",
      time: "5:30 to 8:30pm",
      venue: "Meghnath Saha Hall",
      club: "Photography & Media / Drama Club"),
  FestEvent(
      date: "31th March",
      title: "Qua - Kabaddi (M & W)",
      time: "5:30 to 8:30pm",
      venue: "OAT",
      club: "Student Recreation Club"),
  FestEvent(
      date: "31st March",
      title: "Green Graffitie",
      time: "5:30 to 8:30pm",
      venue: "SAC",
      club: "Literary & Art Club & Environment Club"),
  FestEvent(
      date: "1st April",
      title: "Final - Kabaddi (M & W)",
      time: "5:30 to 8:30pm",
      venue: "OAT",
      club: "Student Recreation Club"),
  FestEvent(
      date: "1st April",
      title: "Puzzle Pulse",
      time: "5:30 to 8:30pm",
      venue: "SAC",
      club: "Literary & Art Club & Environment Club"),
  FestEvent(
      date: "1st April",
      title: "Final - Solo Dance",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Dance Club"),
  FestEvent(
      date: "1st April",
      title: "Final-Solo Singing",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Music Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Mimicry/Standup/Mono Act",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Drama Club"),
  FestEvent(
      date: "3rd April",
      title: "Traditional Day",
      time: "TBD",
      venue: "TBD",
      club: "All Clubs"),
  FestEvent(
      date: "3rd April",
      title: "Final-Group Dance",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Dance Club"),
  FestEvent(
      date: "3rd April",
      title: "Final - Duet Singing & Instrument",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Music Club"),
  FestEvent(
      date: "3rd April",
      title: "Music club-Band night",
      time: "5:00 pm to 9:00pm",
      venue: "OAT",
      club: "Music Club"),
  FestEvent(
      date: "4th April",
      title: "Final Mixed Cricket",
      time: "10:30am to 2:30pm",
      venue: "Ground",
      club: "Outdoor Club & Student Recreation Club"),
  FestEvent(
      date: "4th April",
      title: "Pratibimb & Musical Night",
      time: "5:30 to 9:30pm",
      venue: "Ground",
      club: "All Clubs"),
];