

import 'package:fest_app/core/models/timeline_model.dart';

const List<FestEvent> bihtaEvents = [
  FestEvent(
      date: "14th Feb",
      title: "Qua-Table (M & W)",
      time: "10:30am to 2:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "14th Feb",
      title: "Yoga (M & W)",
      time: "7 am to 9 am",
      venue: "SAC",
      club: "Yoga & Meditation Club"),
  FestEvent(
      date: "15th Feb",
      title: "Sun Day",
      time: "TBD",
      venue: "TBD",
      club: "Not Specified"),
  FestEvent(
      date: "16th Feb",
      title: "Qua-Table (M & W)",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "17th Feb",
      title: "Final Table (M & W)",
      time: "5:30 to 8:30pm",
      venue: "TT Hall",
      club: "Student Recreation Club"),
  FestEvent(
      date: "16th March",
      title: "Qua - Basketball (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Basketball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "16th March",
      title: "Chess (M & W)",
      time: "5:30 to 8:30pm",
      venue: "SAC",
      club: "Student Recreation Club"),
  FestEvent(
      date: "17th March",
      title: "Qua - Basketball (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Basketball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "17th March",
      title: "Chess (M & W)",
      time: "5:30 to 8:30pm",
      venue: "SAC",
      club: "Student Recreation Club"),
  FestEvent(
      date: "18th March",
      title: "Qua - Football (M)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "18th March",
      title: "Power Sports (W)",
      time: "5:30 to 8:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "19th March",
      title: "Qua - Football (M)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "19th March",
      title: "Power Sports (W)",
      time: "5:30 to 8:30pm",
      venue: "Gym",
      club: "Student Recreation Club"),
  FestEvent(
      date: "20th March",
      title: "Qua - Badminton (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "20th March",
      title: "Final Basketball",
      time: "5:30 to 8:30pm",
      venue: "Basketball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "21st March",
      title: "Qua - Badminton (M & W)",
      time: "10:30am to 2:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "21st March",
      title: "Power Sports (M)",
      time: "10:30am to 2:30pm",
      venue: "GYM",
      club: "Student Recreation Club"),
  FestEvent(
      date: "21st March",
      title: "E-Sports - I",
      time: "4:30 to 5:30 pm",
      venue: "TBD",
      club: "Student Recreation Club"),
  FestEvent(
      date: "22nd March",
      title: "Final Badminton (M & W)",
      time: "10:30am to 2:30pm",
      venue: "Badminton Court",
      club: "Student Recreation Club"),
  FestEvent(
      date: "22nd March",
      title: "Power Sports (M) / E-Sports - II",
      time: "10:30am to 2:30pm",
      venue: "GYM",
      club: "Student Recreation Club"),
        FestEvent(
      date: "22st March",
      title: "E-Sports - II",
      time: "TBD",
      venue: "TBD",
      club: "Student Recreation Club"),
  FestEvent(
      date: "23rd March",
      title: "Qua Mixed Cricket",
      time: "5:30 to 8:30pm",
      venue: "Basketball Court",
      club: "Outdoor Club & Student Recreation Club"),
  FestEvent(
      date: "23rd March",
      title: "Final Football",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club"),
  FestEvent(
      date: "24th March",
      title: "Qua - Volleyball (M)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "24th March",
      title: "Qua - Tug of War (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "25th March",
      title: "Qua - Volleyball (M)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "25th March",
      title: "Qua - Tug of War (M & W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "26th March",
      title: "Final Volleyball (M)",
      time: "5:30 to 8:30pm",
      venue: "Volleyball Court",
      club: "Outdoor Club"),
  FestEvent(
      date: "26th March",
      title: "Final Tug of War (M &W)",
      time: "5:30 to 8:30pm",
      venue: "Ground",
      club: "Outdoor Club & Think India"),
  FestEvent(
      date: "26th March",
      title: "Pre-Pratibimb & Pre-Darpan",
      time: "5:30 to 8:30pm",
      venue: "SAC Building",
      club: "All Clubs"),
  FestEvent(
      date: "27th March",
      title: "Pre - Solo Dance",
      time: "5:30 to 8:30pm",
      venue: "LDC",
      club: "Dance Club"),
  FestEvent(
      date: "27th March",
      title: "Pre - Duet Dance",
      time: "5:30 to 8:30pm",
      venue: "LDC",
      club: "Dance Club"),
  FestEvent(
      date: "28th March",
      title: "T-shirt painting & Clay Modelling",
      time: "10:30 am to 1:00 pm",
      venue: "LDC",
      club: "Literary & Art Club"),
  FestEvent(
      date: "28th March",
      title: "Photography Events",
      time: "2:00 pm to 4:00 pm",
      venue: "LDC (Conference Room)",
      club: "Photography & Media Club"),
  FestEvent(
      date: "28th March",
      title: "Environment Quiz",
      time: "4:00 to 6:00 pm",
      venue: "LDC (Conference Room)",
      club: "Environment Club"),
  FestEvent(
      date: "28th March",
      title: "Pre - Mimicry/MonoAct",
      time: "6:00pm to 8:30pm",
      venue: "LDC",
      club: "Drama Club"),
  FestEvent(
      date: "28th March",
      title: "Pre-Standup/StoryTelling",
      time: "6:00 pm to 8:30 pm",
      venue: "LDC",
      club: "Drama Club"),
  FestEvent(
      date: "28th March",
      title: "Pre - Group Act",
      time: "6:00 pm to 8:30 pm",
      venue: "LDC",
      club: "Drama Club"),
  FestEvent(
      date: "29th March",
      title: "Graphika - Designing Events",
      time: "10:30 am to 1:30pm",
      venue: "TBD",
      club: "Photography & Media Club"),
  FestEvent(
      date: "29th March",
      title: "Antakshari",
      time: "2:30 to 5:30pm",
      venue: "LDC (Conference Room)",
      club: "Music Club"),
  FestEvent(
      date: "29th March",
      title: "Impromptu",
      time: "6:00 to 8:30pm",
      venue: "LDC",
      club: "Dance Club"),
  FestEvent(
      date: "30th March",
      title: "Pre Solo Singing",
      time: "5:30 to 7:00pm",
      venue: "LDC",
      club: "Music Club"),
  FestEvent(
      date: "31st March",
      title: "Back Drawing - (Art Event)",
      time: "7:00 to 8:30 pm",
      venue: "LDC",
      club: "Literary & Art Club"),
  FestEvent(
      date: "31st March",
      title: "Pre - Sher o Shayari & Poetry",
      time: "5:30 to 7:30pm",
      venue: "LDC (Conference Room)",
      club: "Literary & Art Club"),
  FestEvent(
      date: "31st March",
      title: "Best From Waste",
      time: "5:30 to 8:30pm",
      venue: "LDC",
      club: "Environment Club"),
  FestEvent(
      date: "1st April",
      title: "Hindi Debate",
      time: "5:30 to 7:30pm",
      venue: "LDC (Conference Room)",
      club: "Think India/Literary and art club"),
  FestEvent(
      date: "1st April",
      title: "Final Mixed Cricket",
      time: "5:30 to 8:30pm",
      venue: "Basketball Court",
      club: "Outdoor Club & Student Recreation Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Sher o Shayari & Poetry",
      time: "5:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Literary & Art Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Solo Dance",
      time: "5:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Dance Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Duet Dance",
      time: "5:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Dance Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Solo Singing",
      time: "5:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Music Club"),
  FestEvent(
      date: "2nd April",
      title: "Final - Darpan",
      time: "5:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "All Clubs"),
  FestEvent(
      date: "3rd April",
      title: "Treasure Hunt",
      time: "9:30 am to 3:30 pm",
      venue: "Amphitheatre Ground",
      club: "All Clubs"),
  FestEvent(
      date: "3rd April",
      title: "Nukkad Natak",
      time: "4:00 to 5:00pm",
      venue: "OAT",
      club: "Drama Club"),
  FestEvent(
      date: "3rd April",
      title: "Final - Mimicry/MonoAct",
      time: "3:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Drama Club"),
  FestEvent(
      date: "3rd April",
      title: "Final - Standup/StoryTelling",
      time: "3:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Drama Club"),
  FestEvent(
      date: "3rd April",
      title: "Final - Group Act",
      time: "3:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "Drama Club"),
  FestEvent(
      date: "3rd April",
      title: "Final - Pratibimb",
      time: "3:30 to 8:30pm",
      venue: "Amphitheatre Ground",
      club: "All Clubs"),
  FestEvent(
      date: "3rd April",
      title: "Musical Night",
      time: "3:30pm to 9:30pm",
      venue: "Amphitheatre Ground",
      club: "GMT"),
];